theme: jekyll-theme-minimal
title: Aplicaciones y Discusiones en Desarrollo Animal - Taller 2
description: Using transcriptomics to study developmental plasticity in non-model organisms
logo: /assets/img/course_logo.png
show_downloads: true
